---
title: "Untitled"
author: "Tom Klotz"
date: "17 8 2023"
output: html_document
---

```{r setup, include=FALSE}
df <- read_delim("politbarometer_zeitreihe.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)
```

### größte Krisen nach Politbarometer
```{r}
df$dates <- as.Date(df$...2, format = "%d.%m.%Y")
df$quarter <- floor_date(df$dates, "quarter")
df$...1 <- NULL
df$...2 <- NULL
df$dats <- NULL
df2013 <- df[df$quarter >= "2013-10-01",]




dfMean <- aggregate(df2013, by = list(df2013$quarter), FUN = mean, na.action = na.omit)

dfMean$dates <- NULL

```

```{r}
dfMean$quarter <- dfMean$Group.1
dfMean$Group.1 <- NULL

dfMelt <- melt(dfMean, id.vars = "quarter")

dfMelt$value <- ifelse(is.na(dfMelt$value),0, dfMelt$value)


ggplot(dfMelt, aes(x = quarter, y = (value/100), group = variable, color = variable))+
        geom_line()+
        labs(x = "Jahre", y = "aggregierter Prozentanteil", color = "Probleme")+
        scale_y_continuous(labels = scales::percent)+
        theme_bw()
        

#Klima, Corona,
#Flüchtlinge
#Arbeitslosigkeit? - bis 2013
#Ukrainekrieg
```
### Corona
```{r}

#remove spalte mit Jahr 2000 und 2023
#rsetzung von NA mit 0
dfSum$Coronavirus[dfSum$Coronavirus == NA] <- 0
```



### Seit 2013 in Jahren
Ukrainekrieg [2022]
Corona[2020]


```{r}
df$date <- paste0(substring(df$...2, 7,11),"-",substring(df$...2,4,5)) #Monate
df2013 <- df[df$date >= 2013,]


dfGroup1 <- df2013%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,date)%>%
  group_by(date)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`)
    #Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )

#mit totals
dfGroup2 <- df2013%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,date)%>%
  group_by(date)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`),
    Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )


```

### Seit 2001 in Jahren
Klima
Flüchtlinge

```{r}

df$year <- substring(df$...2, 7,11)
df2001 <- df[df$year >= 2001,]


df$dates <- as.Date(df$...2, format = "%d.%m.%Y")
df$quarter <- floor_date(df$dates, "quarter")


dfGroup1 <- df2001%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,year)%>%
  group_by(year)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`)
    #Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )
```
### Quarters

```{r}
df <- read_delim("politbarometer_zeitreihe.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

df$dates <- as.Date(df$...2, format = "%d.%m.%Y")
df$quarter <- floor_date(df$dates, "quarter")


dfGroup1 <- df%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,quarter)%>%
  group_by(quarter)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`)
    #Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )


dfMelt <- melt(dfGroup1, id.vars = "quarter")

ggplot(dfMelt, aes(x = quarter, y = value, group = variable, color = variable))+
         geom_line()+
         theme_bw()

```

