---
title: "3. 1 Corona"
output: html_document
date: "2023-08-21"
---
### Corona

```{r}
#corona <- c("Impfgegner", "Covid-19", "SARS-CoV-2", "Pandemie", "China-Virus", "Impfpflicht", "AstraZeneca", "Testzentrum", "Verschwörung(stheorien)", #"Corona-Leugner", "Corona-Klage", "Maskenpflicht","Impfung")



#aussortiert <- c("Meinungsfreiheit","impf*")


corona <- c("pandemie", "corona*", "covid*","lockdown","omikron","mrna","testzentr*")

            

```


```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = corona, separator = " "))

dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)

dates$quarter <- floor_date(dates$date, "quarter")
dates$month <- floor_date(dates$date, "month")
dates$year <- as.numeric(substring(dates$date, 1,4))

dfMerged <- merge(dfKwic,dates)

dfunter2019 <- dfMerged[dfMerged$year < 2019,]
df2019 <- dfMerged[dfMerged$year >= 2019,]

table(dfunter2019$pattern)
table(df2019$pattern)
dfMerged$count <- 1

dfMerged <- dfMerged[dfMerged$quarter >= "2013-10-01",]

dfVis <- dfMerged%>%
  select(quarter, pattern, count)%>%
  group_by(quarter, pattern)%>%
  reframe(count = sum(count))
  


ggplot(dfVis, aes(x = quarter, y = count,color = pattern))+
  geom_line()+
  labs(x = "Quartale", y = "Anzahl", color = "Pattern")
```

```{r}
covdict <- dictionary(list(corona = corona))

dfm <- dfm(toks)

results <- dfm%>%
  dfm_lookup(covdict)

dfCorona <- convert(results, to = "data.frame")

#Quarter
dfCorona$quarter <- floor_date(docvars(dfm)$date, "quarter")


results_corona <- dfCorona %>%
  select(quarter, corona)%>%
  group_by(quarter)%>%
  reframe(
    corona = sum(corona)
  )
#Month
dfCorona$month <- floor_date(docvars(dfm)$date, "month")

results_corona_m <- dfCorona %>%
  select(month, corona)%>%
  group_by(month)%>%
  reframe(
    corona = sum(corona)
  )

```


## Validierung

### Konstruktvalidität

```{r}
dfVal <- merge(results_corona, dfGroup1)

cor(dfVal$corona, dfVal$Corona)
```
### Split-half reliabilität

```{r}
pattern <- corona
reliability <- list()

dfm <- dfm(toks)%>%
  dfm_tolower()

dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)
dates$quarter <- floor_date(dates$date, "quarter")


for (i in c(0:1000)){
  
  half_1 <- sample(
  x = pattern,
  size = round(length(pattern)/2, 0),
  replace = FALSE
  )
  half_1 <- dictionary(list(half_1 = half_1))
  half_2 <- dictionary(list(half_2 = pattern[!(pattern %in% half_1)]))
  
  
  results1 <- dfm%>%
  dfm_lookup(half_1)
  
  results1 <- convert(results1, to = "data.frame")
  results1$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results1 <- results1 %>%
    select(quarter, half_1)%>%
    group_by(quarter)%>%
    reframe(
      half_1 = sum(half_1)
    )
  
  
  results2 <- dfm%>%
  dfm_lookup(half_2)
  
  results2 <- convert(results2, to = "data.frame")
  results2$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results2 <- results2 %>%
    select(quarter, half_2)%>%
    group_by(quarter)%>%
    reframe(
      half_2 = sum(half_2)
    )
  

  relia <- spearman_brown(results1$half_1,  results2$half_2)
  reliability[i] <- relia
}
  
saveRDS(reliability, file = "coronaRelia.RDS") 

mean(unlist(coronaRelia))

min(unlist(coronaRelia))
```


### Wordclouds

```{r}
textplot <- function(text, min_freq = 25){
  text <- gsub("dass","",text)
  dtm <- dfm(text) %>%
    dfm(remove = stopwords('german')) %>%
    dfm_wordstem() %>%
    dfm_trim(min_termfreq = min_freq , verbose = FALSE)
  
  set.seed(100)
  textplot_wordcloud(dtm)
  
}
```

```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = corona, separator = " "))


dfKwic$context <- paste0(dfKwic$pre," ", dfKwic$post)

textplot(dfKwic$context)
```
