---
title: "3.2 flüchtlinge"
output: html_document
date: "2023-08-21"
---

### Corona

```{r}
#flüchtlinge <- c("(Binnen)", "Flüchtling*", "Geflüchtet*", "globaler Flüchtlingspakt", "Syrien", "Migranten*", "Genfer Flüchtlingskonvention", "Flüchtlingslager", "Asylbewerber*", "Asyl", "Aufenthaltserlaubnis", "Einwanderung*", "Aufenthaltstitel", "Illegal", "Herkunftsstaat*", "Dublin-Verordnung","Dublin-Abkommen")


refugee <- c("*flüchtlinge*", "*einwanderung*","migration","asyl","integration")


```


```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = refugee, separator = " "))


dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)

dates$quarter <- floor_date(dates$date, "quarter")
dates$year <- as.numeric(substring(dates$date, 1,4))

dfMerged <- merge(dfKwic,dates)
dfMerged$count <- 1



dfMerged1 <- dfMerged[dfMerged$year <= 2010,]

table(dfMerged$keyword)
table(dfMerged$pattern)
table(dfMerged1$pattern)

### Grafik zu integration

dfMerged <- dfMerged[dfMerged$quarter >= "2013-10-01",]

dfVis <- dfMerged%>%
  select(quarter, pattern, count)%>%
  group_by(quarter, pattern)%>%
  reframe(count = sum(count))
  


ggplot(dfVis, aes(x = quarter, y = count,color = pattern))+
  geom_line()+
  labs(x = "Quartale", y = "Anzahl", color = "Pattern")

```

```{r}
refugeedict<- dictionary(list(refugee = refugee))

dfm <- dfm(toks)

results <- dfm%>%
  dfm_lookup(refugeedict)

dfRefugee <- convert(results, to = "data.frame")

dfRefugee$quarter <- floor_date(docvars(dfm)$date, "quarter")

results_refugee <- dfRefugee %>%
  select(quarter, refugee)%>%
  group_by(quarter)%>%
  reframe(
    refugee = sum(refugee)
  )

#Month
dfRefugee$month <- floor_date(docvars(dfm)$date, "month")

results_refugee_m <- dfRefugee %>%
  select(month, refugee)%>%
  group_by(month)%>%
  reframe(
    refugee = sum(refugee)
  )
```


## Validierung

### Konstruktvalidität

```{r}
dfVal <- merge(results_refugee, dfGroup1)

cor(dfVal$refugee, dfVal$Flüchtlinge)

# 0.7218827
```
### Split-half reliabilität

```{r}
pattern <- refugees
reliability <- list()

dfm <- dfm(toks)%>%
  dfm_tolower()

dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)
dates$quarter <- floor_date(dates$date, "quarter")


for (i in c(0:2)){
  
  half_1 <- sample(
  x = pattern,
  size = round(length(pattern)/2, 0),
  replace = FALSE
  )
  half_1 <- dictionary(list(half_1 = half_1))
  half_2 <- dictionary(list(half_2 = pattern[!(pattern %in% half_1)]))
  
  
  results1 <- dfm%>%
  dfm_lookup(half_1)
  
  results1 <- convert(results1, to = "data.frame")
  results1$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results1 <- results1 %>%
    select(quarter, half_1)%>%
    group_by(quarter)%>%
    reframe(
      half_1 = sum(half_1)
    )
  
  
  results2 <- dfm%>%
  dfm_lookup(half_2)
  
  results2 <- convert(results2, to = "data.frame")
  results2$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results2 <- results2 %>%
    select(quarter, half_2)%>%
    group_by(quarter)%>%
    reframe(
      half_2 = sum(half_2)
    )
  

  relia <- spearman_brown(results1$half_1,  results2$half_2)
  reliability[i] <- relia
}
  
saveRDS(reliability, file = "refugeeRelia.RDS") 

mean(unlist(refugeeRelia))

min(unlist(refugeeRelia))
```

### Wordclouds

```{r}
textplot <- function(text, min_freq = 25){
  text <- gsub("dass","",text)
  dtm <- dfm(text) %>%
    dfm(remove = stopwords('german')) %>%
    dfm_wordstem() %>%
    dfm_trim(min_termfreq = min_freq , verbose = FALSE)
  
  set.seed(100)
  textplot_wordcloud(dtm)
  
}
```

```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = refugees, separator = " "))


dfKwic$context <- paste0(dfKwic$pre," ", dfKwic$post)

textplot(dfKwic$context)
```
