---
title: "3.2 klima"
output: html_document
date: "2023-08-21"
---

```{r}
klima <- c("letzte Generation", "Klimakleber", "Frust", "Energiekrise", "Fridays-For-Future/ FFF", "Extinction Rebellion", "1,5 Grad Ziel", "Überwärmung/ Überhitztung", "Gletscher schmelzen", "Klimakatastrophe", "Pariser(-)Konvention")
```


```{r}

klima <- c("klima*","fridays","erderwärmung","erderhitzung","energiekrise","energieknappheit", "*versorgungssicherheit","energieversorgung")

#"erneuerbareenergien*"
# ,"regenerativ*"
#"erneuerbar*"
#"energiewende"
#"energieversorgung"
#, "*treibhaus*"
```

```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = klima, separator = " "))


dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)

dates$quarter <- floor_date(dates$date, "quarter")
dates$year <- as.numeric(substring(dates$date, 1,4))

dfMerged <- merge(dfKwic,dates)
dfMerged$count <- 1



dfMerged <- dfMerged[dfMerged$quarter >= "2013-10-01",]
table(dfMerged$keyword)
table(dfMerged$pattern)

dfVis <- dfMerged%>%
  select(quarter, pattern, count)%>%
  group_by(quarter, pattern)%>%
  reframe(count = sum(count))
  


ggplot(dfVis, aes(x = quarter, y = count,color = pattern))+
  geom_line()+
  labs(x = "Quartale", y = "Anzahl", color = "Pattern")
```



```{r}
klimadict<- dictionary(list(klima = klima))


dfm <- dfm(toks)

results <- dfm%>%
  dfm_lookup(klimadict)

dfKlima <- convert(results, to = "data.frame")

dfKlima$quarter <- floor_date(docvars(dfm)$date, "quarter")

results_klima <- dfKlima %>%
  select(quarter, klima)%>%
  group_by(quarter)%>%
  reframe(
    klima = sum(klima)
  )

```


## Validierung

### Konstruktvalidität

```{r}
dfVal <- merge(results_klima, dfGroup1)

cor(dfVal$klima, dfVal$Klima)
```
### Split-half reliabilität

```{r}
pattern <- klima
reliability <- list()

dfm <- dfm(toks)%>%
  dfm_tolower()

dates <- data.frame(docname = docnames(toks), date = docvars(toks)$date)
dates$quarter <- floor_date(dates$date, "quarter")


for (i in c(0:2)){
  
  half_1 <- sample(
  x = pattern,
  size = round(length(pattern)/2, 0),
  replace = FALSE
  )
  half_1 <- dictionary(list(half_1 = half_1))
  half_2 <- dictionary(list(half_2 = pattern[!(pattern %in% half_1)]))
  
  
  results1 <- dfm%>%
  dfm_lookup(half_1)
  
  results1 <- convert(results1, to = "data.frame")
  results1$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results1 <- results1 %>%
    select(quarter, half_1)%>%
    group_by(quarter)%>%
    reframe(
      half_1 = sum(half_1)
    )
  
  
  results2 <- dfm%>%
  dfm_lookup(half_2)
  
  results2 <- convert(results2, to = "data.frame")
  results2$quarter <- floor_date(docvars(dfm)$date, "quarter")

  results2 <- results2 %>%
    select(quarter, half_2)%>%
    group_by(quarter)%>%
    reframe(
      half_2 = sum(half_2)
    )
  

  relia <- spearman_brown(results1$half_1,  results2$half_2)
  reliability[i] <- relia
}
  
saveRDS(reliability, file = "klimaRelia.RDS") 

mean(unlist(klimaRelia))

min(unlist(klimaRelia))
```

### Wordclouds

```{r}
textplot <- function(text, min_freq = 25){
  text <- gsub("dass","",text)
  dtm <- dfm(text) %>%
    dfm(remove = stopwords('german')) %>%
    dfm_wordstem() %>%
    dfm_trim(min_termfreq = min_freq , verbose = FALSE)
  
  set.seed(100)
  textplot_wordcloud(dtm)
  
}
```

```{r}
dfKwic <- as.data.frame(kwic(toks,
           pattern = phrase(klima), separator = " "))


dfKwic$context <- paste0(dfKwic$pre," ", dfKwic$post)

textplot(dfKwic$context)
```

