---
title: "Untitled"
output: html_document
date: "2023-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

df <- read_delim("politbarometer_zeitreihe.csv", 
    delim = ";", escape_double = FALSE, trim_ws = TRUE)

```


```{r}
df$date <- paste0(substring(df$...2, 7,11),"-",substring(df$...2,4,5))
df <- df[df$date >= 2013,]


dfGroup1 <- df%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,date)%>%
  group_by(date)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`)
    #Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )

dfGroup2 <- df%>%
  select(`Energie/Versorgung/Klima`,Coronavirus,`Ausländer/Integration/Flüchtlinge`,`Ukraine/Krieg/Russland`,date)%>%
  group_by(date)%>%
    mutate(`Energie/Versorgung/Klima`= if_else(is.na(`Energie/Versorgung/Klima`), 0, `Energie/Versorgung/Klima`))%>%
    mutate(Coronavirus= if_else(is.na(Coronavirus), 0, Coronavirus))%>%
    mutate(`Ausländer/Integration/Flüchtlinge`= if_else(is.na(`Ausländer/Integration/Flüchtlinge`), 0, `Ausländer/Integration/Flüchtlinge`))%>%
    mutate(`Ukraine/Krieg/Russland`= if_else(is.na(`Ukraine/Krieg/Russland`), 0, `Ukraine/Krieg/Russland`))%>%
  reframe(
    Flüchtlinge = mean(`Ausländer/Integration/Flüchtlinge`),
    Klima = mean(`Energie/Versorgung/Klima`),
    Corona = mean(Coronavirus),
    UkraineKrieg = mean(`Ukraine/Krieg/Russland`),
    Total = sum(Corona) + sum(Flüchtlinge) + sum(Klima) + sum(UkraineKrieg)
  )

  
```

# Populismus

```{r}

#install.packages("devtools")
devtools::install_github("jogrue/regexhelpeR")
devtools::install_github("jogrue/multidictR")
devtools::install_github("jogrue/popdictR")
needed.packages <- c("quanteda", "tidyverse", "devtools", "regexhelpeR", "multidictR", "popdictR","stringr")
invisible(lapply(needed.packages, library, character.only = TRUE))


# Daten einlesen ---------------------------------------------------------------



speeches2001 <- readRDS("~/R/R Projekte/crisesdictR/speeches/speeches2001.RDS")

raw_corpus <- corpus(speeches2001, text_field = 6) 



results <- run_popdict(raw_corpus, return_value = "count_at_level")
saveRDS(results, file = "results2001.RDS")

results_dataframe <- convert(results, to = "data.frame")
results_dataframe$date_month <- str_sub(results_dataframe$date, end = -4)


### Continued ------------------------------------------------------------------

summary2 <- results_dataframe %>%
  group_by(date_month) %>%
  reframe(sentences = sum(n_sentences),
            gruendl = sum(dict_gruendl_2020) / sentences * 100) %>%
  ungroup


```

# Sentiments



....



### Massenpolarisierung

```{r}
library(haven)
poladata <- read_sav("ZA2391_v14-0-0.sav")

poladata <- poladata %>%
  filter(v4 >= 2013)

poladata <- poladata %>%
  select(v3, v4, v22 )

#das datum muss korrigiert werden
library(stringr)
poladata$v3 <- str_pad(poladata$v3, 2, pad = "0")
poladata$v3 <- str_pad(poladata$v3, 3, pad = "-")

poladata$date <- paste(poladata$v4, poladata$v3, sep = "")

poladata$v22[poladata$v22 == 99] <- NA
poladata <- na.omit(poladata)

poladata <- poladata %>%
  select(v22, date)

summary_3 <- poladata %>%
  group_by(date) %>%
  summarise(sd_leftright = sd(v22))

summary_3 <- summary_3 %>%
  mutate(sd_leftright_z = scale(sd_leftright))
##so, fertig.

is.numeric(summary_3$sd_leftright_z)

ggplot(summary_3, aes(x = date, y = sd_leftright_z, group = 1, color = sd_leftright))+
  geom_line()+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90))

summary_3

```



## Merge Data
```{r}
dfMerged <- merge(summary2, dfGroup2, by.x = "date_month", by.y = "date")
dfMerged <- merge(dfMerged, summary_3,  by.x = "date_month", by.y = "date")
dfMerged <- dfMerged[dfMerged$sentences > 1000,] #remove month with low speeches

### z-transformation 

dfMerged$Total_z <- scale(dfMerged$Total, center = T)
dfMerged$gruendl_z <- scale(dfMerged$gruendl, center = T)



```



### Grafik

#### Deskriptive Krisen Darstellung
```{r}
dfMelt <- reshape2::melt(dfGroup2, id.vars = "date")


ggplot(dfMelt, aes(x = date, y =value, group = variable, color = variable))+
         geom_line()+
         theme_bw()+
         theme(axis.text.x = element_text(angle = 180))
       
```


```{r}

dfMerged_z <- select(dfMerged, date_month, Total_z, gruendl_z, sd_leftright_z )

dfMelt <- reshape2::melt(dfMerged_z, id.vars = "date_month")

ggplot(dfMelt, aes(x = date_month, y =value, group = variable, color = variable))+
         geom_line()+
         theme_bw()+
         theme(axis.text.x = element_text(angle = 90))
```


### Regressionen

```{r}
#AfD enters the parliament split
dfMerged_z1 <- dfMerged_z[dfMerged_z$date_month < "2017-09",]
dfMerged_z2 <- dfMerged_z[dfMerged_z$date_month > "2017-09",] 

#Total period
fit <- lm(gruendl_z ~ Total_z + sd_leftright_z, data = dfMerged_z)
summary(fit)

fit1 <- lm(gruendl_z ~ Total_z + sd_leftright_z, data = dfMerged_z1)
summary(fit1)

fit2 <- lm(gruendl_z ~ Total_z + sd_leftright_z, data = dfMerged_z2)
summary(fit2)
```
